// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants

const spandanaSpoorthy = {
  //aws_app_analytics: "disable",
  aws_auth_facebook: "enable",
  aws_cloud_logic: "enable",
  aws_cloud_logic_custom: [
    {
      id: "kqd29za2e4",
      name: "EN-PLATFORM",
      description: "",
      endpoint:
        "https://kqd29za2e4.execute-api.ap-south-1.amazonaws.com/EN938437",
      region: "ap-south-1",
    },
  ],
  aws_cloud_logic_custom_E: [
    {
      id: "kqd29za2e4",
      name: "EN-PLATFORM",
      description: "",
      endpoint:
        "https://kqd29za2e4.execute-api.ap-south-1.amazonaws.com/EN938437",
      region: "ap-south-1",
    },
  ],
  aws_cloud_logic_custom_name: "EN-PLATFORM",
  aws_cloud_logic_custom_name_E: "EN-PLATFORM",
  aws_cognito_identity_pool_id:
    "us-east-1:8909746a-d836-4369-aef7-b7cd76a77c66",
  aws_cognito_region: "ap-south-1",
  aws_content_delivery: "enable",
  // aws_content_delivery_bucket: "jeevaraksha-resources",
  aws_content_delivery_bucket_region: "ap-south-1",
  aws_content_delivery_cloudfront: "enable",
  aws_content_delivery_cloudfront_domain: "www.ssfl.enabled.live",
  // aws_facebook_app_id: "281569732265049",
  // aws_facebook_app_permissions: "public_profile",
  aws_mandatory_sign_in: "enable",
  aws_project_region: "ap-south-1",
  // aws_resource_name_prefix: "jeevaraksha-resources",
  aws_sign_in_enabled: "enable",
  aws_user_pools: "enable",
  aws_push_apns: "enable",
  aws_push_pinpoint: "enable",
  aws_user_pools_id: "ap-south-1_B9DugKdVH",
  aws_user_pools_web_client_id: "1clgtf70851u6smmisss6hlhq7",
  aws_cloud_logic_custom_endpoint:
    "https://kqd29za2e4.execute-api.ap-south-1.amazonaws.com/",
  aws_schema: "spandana",
  aws_schema_E: "spandana",
  aws_org_id: "SPANDANA",
  aws_org_id_E: "SPANDANA",
  aws_user_pools_id_E: "ap-south-1_B9DugKdVH",
  aws_user_pools_web_client_id_E: "1clgtf70851u6smmisss6hlhq7",
  aws_content_delivery_cloudfront_domain_E: "www.ssfl.enabled.live",
  aws_cognito_identity_pool_id_E:
    "us-east-1:8909746a-d836-4369-aef7-b7cd76a77c66",
  aws_cloud_logic_custom_endpoint_E:
    "https://kqd29za2e4.execute-api.ap-south-1.amazonaws.com/EN938437",
  aws_ctype: 0,
  aws_ctype_E: 0,
  title: "Spandana-Sphoorty",
  aws_cloud_logic_custom_E1: [
    {
      id: "kqd29za2e4",
      name: "EN-PLATFORM",
      description: "",
      endpoint:
        "https://kqd29za2e4.execute-api.ap-south-1.amazonaws.com/EN938437",
      region: "ap-south-1",
    },
  ],
};

export default spandanaSpoorthy;
